spring.application.name=online-store

# Base configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${STORE_DB_URL}
spring.datasource.username=${STORE_DB_USERNAME}
spring.datasource.password=${STORE_DB_PASSWORD}
logging.level.org.hibernate.persister.entity=ERROR
spring.mvc.hiddenmethod.filter.enabled=true
spring.data.web.pageable.one-indexed-parameters=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG